name: update-idf-git

on:
  workflow_dispatch:
    inputs:
      git_version:
        description: 'Git version'
        required: true
        default: '2.39.2'

jobs:
  upload-idf-python:
    name: Upload IDF Python
    runs-on: ubuntu-latest
    steps:
      - name: Download IDF Python
        shell: bash
        run: curl -L https://github.com/git-for-windows/git/releases/download/v${{ github.event.inputs.git_version }}.windows.1/MinGit-${{ github.event.inputs.git_version }}-64-bit.zip -o git.zip
      - name: Upload Release Asset To dl.espressif.com
        id: upload-release-asset-espressif
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        shell: pwsh
        run: aws s3 cp --acl=public-read --no-progress git.zip s3://${{ secrets.DL_BUCKET }}/dl/idf-git/idf-git-${{ github.event.inputs.git_version }}-win64.zip
      - name: Invalidate cache
        id: invalidate-index-cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DL_DISTRIBUTION_ID }} --paths "/dl/idf-git/idf-git-${{ github.event.inputs.git_version }}-win64.zip"
