name: update-idf-python

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version'
        required: true
        default: '3.11.2'

jobs:
  upload-idf-python:
    name: Upload IDF Python
    runs-on: ubuntu-latest
    steps:
      - name: Download IDF Python
        shell: bash
        run: curl -L https://github.com/espressif/idf-python/releases/download/v${{ github.event.inputs.python_version }}/idf-python-${{ github.event.inputs.python_version }}-embed-win64.zip -o python.zip
      - name: Upload Release Asset To dl.espressif.com
        id: upload-release-asset-espressif
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        shell: pwsh
        run: aws s3 cp --acl=public-read --no-progress python.zip s3://${{ secrets.DL_BUCKET }}/dl/idf-python/idf-python-${{ github.event.inputs.python_version }}-embed-win64.zip
      - name: Invalidate cache
        id: invalidate-index-cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DL_DISTRIBUTION_ID }} --paths "/dl/idf-python/idf-python-${{ github.event.inputs.python_version }}-win64.zip"
